title: Task Utitily GitIgnore
commands:
  -
    init_bare_repo:
      bare: remotes/task_gitignore
      clone_to: task_gitignore
  -
    execute_autogit_tasks:
      skip: False
      tasks:
        - task21/base_repo