title: Task Utitily Submodules
commands:
  -
    init_bare_repo:
      bare: remotes/task9b_submodules
      clone_to: task9b_submodules
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - workshop_2_git_utility/base_repo
  -
    git:
      command: "git checkout main"
  -
    git:
      command: "git -c protocol.file.allow=always submodule add ../company_utils"
  -
    git:
      command: "git add .gitmodules company_utils"
  -
    git:
      command: "git commit -m \"added company utility repo as a submodule\""
  -
    git:
      command: "git push"





