title: Task Utitily Stash
commands:
  -
    init_bare_repo:
      bare: remotes/task7_stash
      clone_to: task7_stash
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - workshop_2_git_utility/base_repo
  # ------------
  # for this task, we start from the feature/config branch and make some
  # changes in the working directory that we can use to explore the behavior
  # of git stash
  # ------------
  -
    git:
      command: "git checkout feature/config"
  -
    create_file:
      source: files/generator_v7.py
      target: generator.py



