title: Task Utitily Submodules (raw repo for adding subrepo)
commands:
  -
    init_bare_repo:
      bare: remotes/task9_submodules
      clone_to: task9_submodules
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - workshop_2_git_utility/base_repo