title: Task Utitily Reset
commands:
  -
    init_bare_repo:
      bare: remotes/task5_revert
      clone_to: task5_revert
  # start from the utility base repository with feature/api, feature/config and feature/hashstore branches
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - workshop_2_git_utility/base_repo
  # ------------
  # for this task, we start from the feature/api branch; idea is that
  # we revert a change that was made here some time ago where the api endpoint names were
  # changed from /password to /pwd;
  # ------------
  -
    git:
      command: "git checkout feature/api"

