title: Task Utitily Worktree
commands:
  -
    init_bare_repo:
      bare: remotes/task8_worktree
      clone_to: task8_worktree
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - workshop_2_git_utility/base_repo