title: Task 4
# Idea of the task: create new feature branch and do some code changes to work with add commit push --> then merge to master
# Important: starting from a ready feature branch that is behind master but causes no merge conflict --> merge from master into feature branch to have current code base
commands:
  -
    init_bare_repo:
      bare: remotes/task4
      clone_to: task4
  -
    execute_autogit_tasks:
      skip: False
      tasks:
        - task3
  -
    git:
      command: "git pull"
  -
    mv:
      source: main.py
      target: generator.py
  -
    commit:
      message: rename main.py
      author: red
  -
    create_add_commit:
      source: files/generator_v1.py
      target: generator.py
      message: re-implemented functionality from main.py as a class (initial version)
      author: red
  -
    create_add_commit:
      source: files/generator_v2.py
      target: generator.py
      message: added seed as parameter in constructor
      author: red
  -
    create_add_commit:
      source: files/generator_v3.py
      target: generator.py
      message: added some comments
      author: red
  -
    create_add_commit:
      source: files/main_v1.py
      target: main.py
      message: Create main.py for execution of the password generator
      author: red
  -
    git:
      command: "git push origin master"

    # now the second developer betty starts with feature development
    # and creates the first generator class; she creates a new feature branch
    # and commits generator.py to it (and pushes it also)
  -
    git:
      command: "git checkout -b feature/generator_with_random_numbers_and_letters_1"
  -
    create_add_commit:
      source: files/generator_v4.py
      target: generator.py
      message: Use letters and numbers for password generation
      author: blue
  -
    create_add_commit:
      files:
        - files/generator_v5.py => generator.py
        - files/main_v2.py => main.py
      message: Create separate method for password generation
      author: blue
  -
    git:
      command: "git push -u origin feature/generator_with_random_numbers_and_letters_1"
  -
    git:
      command: "git checkout -b feature/generator_with_random_numbers_and_letters_2"
  -
    git:
      command: "git push -u origin feature/generator_with_random_numbers_and_letters_2"
  -
    git:
      command: "git checkout master"

  - create_add_commit:
      source: files/generator_v6.py
      target: generator.py
      message: Change default seed
      author: red
  -
    git:
      command: "git push origin master"
  -
    git:
      command: "git checkout feature/generator_with_random_numbers_and_letters_1"