title: remove_and_commit_test
# Idea of the task: create new feature branch and do some code changes to work with add commit push --> then merge to master
commands:
  -
    init_bare_repo:
      bare: remotes/remove_and_commit_test
      clone_to: remove_and_commit_test
  -
    create_add_commit:
      files:
        - files/hello.py => hello.py
        - files/notes-timeline.txt => notes-timeline.txt
      message: hello world
      author: red
  -
    remove_and_commit:
      files: 
      - notes-timeline_nonexistent.txt
      message: clean up timeline notes that don't exist (this step should fail)
      author: red