title: Workshop 2 Task 2
# Idea of the task: Playing a bit with the drop rebase commit option
# Therefore two feature branches are used.
# One is based on the other, so when changes of the first one are merged to master,
# the other needs a rebase because of left commits of the merged branch.
# Branch is adding some README file (like Task 7) to have something easily adjustable.
commands:
  -
    init_bare_repo:
      bare: remotes/task2.2
      clone_to: task2.2

  -
    create_add_commit:
      files:
        - files/generator_v1.py => generator.py
        - files/main_v1.py => main.py
      message: Create password generator project
      author: blue

  -
    git:
      command: "git checkout -b feature/add_readme"

  -
    create_add_commit:
      files:
        - files/README_v1.md => README.md
      message: Create README file
      author: red

  -
    create_add_commit:
      files:
        - files/README_v2.md => README.md
      message: Wip
      author: red

  -
    create_add_commit:
      files:
        - files/README_v3.md => README.md
      message: Add first usage README text lines
      author: red

  -
    create_add_commit:
      files:
        - files/README_v4.md => README.md
      message: Add description of keyword arguments
      author: red

  -
    create_add_commit:
      files:
        - files/README_v5.md => README.md
      message: Fix typo
      author: red

  -
    create_add_commit:
      files:
        - files/README_v6.md => README.md
      message: WIP
      author: red

  -
    git:
      command: "git push -u origin feature/add_readme"

  -
    git:
      command: "git checkout -b feature/extend_readme_with_motivation_1"

  -
    create_add_commit:
      files:
        - files/README_v7.md => README.md
      message: WIP motivation
      author: blue

  -
    create_add_commit:
      files:
        - files/README_v8.md => README.md
      message: Add a motivation section
      author: blue

  -
    create_add_commit:
      files:
        - files/README_v9.md => README.md
      message: Adjust formatting regarding the section title sizes
      author: blue

  -
    git:
      command: "git push -u origin feature/extend_readme_with_motivation_1"

  -
    git:
      command: "git checkout -b feature/extend_readme_with_motivation_2"

  -
    git:
      command: "git push -u origin feature/extend_readme_with_motivation_2"

  -
    git:
      command: "git checkout -b feature/extend_readme_with_motivation_3"

  -
    git:
      command: "git push -u origin feature/extend_readme_with_motivation_3"

  -
    git:
      command: "git checkout master"

  -
    git:
      command: "git merge --squash feature/add_readme"

  -
    git:
      command: "git commit -m \"Merge feature/add_readme branch to master\""

  -
    git:
      command: "git push -u origin master"