title: Task Utitily Reset
commands:
  -
    init_bare_repo:
      bare: remotes/task_reset
      clone_to: task_reset
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - task21/base_repo
  # ------------
  # for this task, we start from the feature/config branch and make some
  # changes in the working directory that we can use to explore the behavior
  # of git reset with different options (soft, mixed, hard)
  # ------------
  -
    git:
      command: "git checkout feature/config"
  -
    create_file:
      source: files/generator_v7.py
      target: generator.py



