title: Task Utitily Reset
commands:
  -
    init_bare_repo:
      bare: remotes/task_reset
      clone_to: task_reset
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - task21/base_repo
  # ------------
  # for this task, we start from the feature/config branch
  # the config user has accidently added and commited a bunch of files
  # there were not intended for the given commit, namely the stuff in
  # docs and testdata folder
  # ------------
  -
    git:
      command: "git checkout feature/config"
  -
    create_add_commit:
      files: 
      - files/docs/ => .docs/
      - files/testdata/ => .testdata/
      - files/generator_v8.py => generator_v8.py
      message: last -- updated generator to use chars from config
      author: config  


