title: Task 6
# Idea of the task: Do the same as for task 3, but with rebase instead of merge --> merge after rebase
commands:
  -
    init_bare_repo:
      bare: remotes/task6
      clone_to: task6
  -
    execute_gitalchemist_tasks:
      skip: False
      tasks:
        - task5