on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

permissions: 
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  autogit-tests:
    name: Run command tests
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Command Self Test
        run: |
          pytest --junitxml=junit.xml
      
      - name: Junit Report ${{ matrix.os }}
        uses: dorny/test-reporter@v1
        with:
          name: AutoGit test report ${{ matrix.os }}
          path: "**/junit.xml"
          reporter: java-junit
